### PR TITLE
switching driver time to use WallTime to enable using the driver with sim time.

### PR DESCRIPTION
**Pull request by futureneer**

### CODE REVIEW

**Comment by aleeper** [comment]
Thanks for the PR.

I haven't worked much with simulation and WallTime. Does using WallTime over just Time have any disadvantages or other repercussions?

**Comment by tfoote** [comment]
This is the recommended technique for hardware devices since they need to keep their event loops tied to the physical system. The biggest issue is how to syncronize stamped outputs. But the loop with the timeouts is much better to keep on WallTime.

**Comment by tfoote** [comment]
+1 reading the diff

**Comment by chadrockey** [comment]
+1 this does exactly what you want.  wallTime is good for when you need actual timed loops (such as polling hardware, running watchdogs, and so on).

I double checked and the node itself still publishes the data using ros::Time, which is correct.  This will publish data that's compatible with use_sim_time true, but at the correct polling rates to the actual controller.

**Comment by aleeper** [comment]
Cool, seems to work for me. Merging.

**Pull request merged**
